(()=>{
if(window.__auroraDashboardV14)return;window.__auroraDashboardV14=true;
const CLOSE_API14='https://oyuprxoqhhnpcnxgaokj.supabase.co/functions/v1/aurora-fechamento';
const PRIV_KEY='aurora_ocultar_receita';
let HIDE=localStorage.getItem(PRIV_KEY)==='1';
const q=s=>document.querySelector(s);
const nn=v=>v===null||v===undefined||v===''||Number.isNaN(Number(v))?null:Number(v);
const money=v=>nn(v)===null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pc=v=>`${Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');css.textContent=`
.dash-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:20px 0 12px}.dash-head h2{margin:0;font-size:24px}.dash-head p{margin:4px 0 0;color:var(--m);font-size:12px}.privacy-btn{display:inline-flex;gap:7px;align-items:center;background:#fff;color:var(--x);border:1px solid var(--l);border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer}.privacy-btn.on{background:#0b1f36;color:#fff;border-color:#0b1f36}.dash-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.metric{background:#fff;border:1px solid var(--l);border-radius:15px;padding:15px;min-height:118px;position:relative;overflow:hidden}.metric:before{content:'';position:absolute;left:0;top:0;bottom:0;width:4px;background:#cbd5e1}.metric.teal:before{background:#0f766e}.metric.blue:before{background:#2563eb}.metric.green:before{background:#16a34a}.metric.orange:before{background:#f59e0b}.metric.red:before{background:#dc2626}.metric small{display:block;color:var(--m);font-size:11px;font-weight:700}.metric strong{display:block;font-size:24px;line-height:1.08;margin-top:8px}.metric .sub{font-size:10px;color:var(--m);margin-top:7px;line-height:1.35}.metric .split{display:flex;gap:9px;flex-wrap:wrap;margin-top:7px}.metric .chip{font-size:9px;background:#f1f5f9;border-radius:999px;padding:4px 7px}.money-mask{letter-spacing:.12em}.dash-row{display:grid;grid-template-columns:1.15fr .85fr;gap:12px;margin-top:12px}.dash-card{background:#fff;border:1px solid var(--l);border-radius:15px;padding:16px}.dash-card h3{margin:0;font-size:16px}.dash-card>p{margin:4px 0 12px;color:var(--m);font-size:11px}.progress-list{display:grid;gap:10px}.progress-item{display:grid;grid-template-columns:minmax(120px,1fr) 80px 1.5fr;gap:9px;align-items:center;font-size:11px}.progress-item b{font-size:11px}.bar{height:9px;background:#edf2f7;border-radius:999px;overflow:hidden}.bar>span{display:block;height:100%;background:#0f766e;border-radius:999px}.status-list{display:grid;gap:9px}.status-item{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:10px 11px;border:1px solid #edf2f7;border-radius:11px}.status-item b{font-size:12px}.status-item span{font-size:11px;color:var(--m)}.dash-note{margin-top:12px;background:#effcf9;border:1px solid #b7eee5;border-radius:13px;padding:12px 14px;font-size:11px;color:#0f5d57;line-height:1.45}.dash-loading{padding:24px;background:#fff;border:1px solid var(--l);border-radius:14px;color:var(--m)}
@media(max-width:1200px){.dash-grid{grid-template-columns:repeat(2,1fr)}.dash-row{grid-template-columns:1fr}.progress-item{grid-template-columns:150px 70px 1fr}}
@media(max-width:650px){.dash-grid{grid-template-columns:1fr}.dash-head{align-items:flex-start;flex-direction:column}.progress-item{grid-template-columns:1fr 60px}.progress-item .bar{grid-column:1/-1}}
`;document.head.appendChild(css);

function masked(v){return HIDE?'<span class="money-mask">••••••••</span>':money(v)}
function setPrivacyButton(){let b=q('#privacyRevenue');if(!b)return;b.classList.toggle('on',HIDE);b.innerHTML=HIDE?'👁 Mostrar valores':'◉ Ocultar valores'}
function ensureTopButton(){let acts=q('.acts');if(!acts||q('#privacyRevenue'))return;let b=document.createElement('button');b.id='privacyRevenue';b.type='button';b.className='privacy-btn';b.onclick=()=>{HIDE=!HIDE;localStorage.setItem(PRIV_KEY,HIDE?'1':'0');setPrivacyButton();if(active==='dash')renderDashboard()};acts.insertBefore(b,acts.firstChild);setPrivacyButton()}
async function closingRows(){let r=await fetch(CLOSE_API14,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action:'list',ano:2027}),cache:'no-store'}),d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'fechamento_failed');return d.rows||[]}
async function secretary(){try{return await api('secretary')}catch{return {profiles:[],guardians:[],enrollments:[]}}}
function uniqueEnrollments(rows){let m=new Map();for(const e of rows||[]){if(Number(e.ano_letivo)!==2027)continue;let key=e.student_id||e.id,prev=m.get(key);if(!prev||String(e.updated_at||'')>String(prev.updated_at||''))m.set(key,e)}return [...m.values()]}
function turmaDist(enrollments){let o={};for(const e of enrollments){let t=e.serie||'Sem turma';o[t]=(o[t]||0)+1}return Object.entries(o).sort((a,b)=>String(a[0]).localeCompare(String(b[0]),'pt-BR'))}
function sereiStats(){let a=S?.students||[],sim=0,nao=0,analise=0;for(const s of a){let x=String(s.serei2027||s.serei_2027||'em_analise');if(x==='sim')sim++;else if(x==='nao')nao++;else analise++}return{sim,nao,analise,total:a.length}}
async function renderDashboard(){ensureTopButton();let host=q('#dash');if(!host)return;host.innerHTML='<div class="dash-loading">Atualizando indicadores da Gestão Aurora...</div>';let [secD,closeD]=await Promise.allSettled([secretary(),closingRows()]);let sd=secD.status==='fulfilled'?secD.value:{enrollments:[]},cl=closeD.status==='fulfilled'?closeD.value:[];let enroll=uniqueEnrollments(sd.enrollments||[]),students=S?.students||[],st=sereiStats();
 let receita2026=students.reduce((a,s)=>a+(nn(s.totalPago2026)||0),0);let paid2026=students.filter(s=>nn(s.totalPago2026)!==null).length;let ticket2026=paid2026?receita2026/paid2026:0;
 let veteranos=enroll.filter(e=>String(e.tipo_aluno||'').toLowerCase().includes('veter')).length,novatos=enroll.filter(e=>!String(e.tipo_aluno||'').toLowerCase().includes('veter')).length;
 let mensal2027=enroll.reduce((a,e)=>a+(nn(e.mensalidade_negociada)||0),0),mat2027=enroll.reduce((a,e)=>a+(nn(e.valor_matricula)||0),0);
 let complete=cl.filter(r=>nn(r.valor_matricula)!==null&&nn(r.valor_mensalidade)!==null).length,pending=Math.max(0,cl.length-complete),coverage=cl.length?complete/cl.length*100:0;
 let confirmRate=st.total?st.sim/st.total*100:0,reenrollRate=students.length?veteranos/students.length*100:0,dist=turmaDist(enroll),max=Math.max(1,...dist.map(x=>x[1]));
 host.innerHTML=`<div class="dash-head"><div><h2>Dashboard executivo</h2><p>Indicadores da Secretaria, Financeiro e Gestão em uma única visão.</p></div><button id="dashPrivacy" class="privacy-btn ${HIDE?'on':''}">${HIDE?'👁 Mostrar valores':'◉ Ocultar valores'}</button></div>
 <div class="dash-grid">
  <div class="metric blue"><small>Base de alunos 2026</small><strong>${students.length}</strong><div class="sub">${paid2026} com valor financeiro registrado</div></div>
  <div class="metric teal"><small>Receita registrada 2026</small><strong>${masked(receita2026)}</strong><div class="sub">Ticket médio registrado: ${masked(ticket2026)}</div></div>
  <div class="metric green"><small>Matrículas / rematrículas 2027</small><strong>${enroll.length}</strong><div class="split"><span class="chip">${veteranos} veteranos</span><span class="chip">${novatos} novatos</span></div><div class="sub">Taxa de rematrícula sobre a base 2026: ${pc(reenrollRate)}</div></div>
  <div class="metric orange"><small>Serei 2027</small><strong>${st.sim} confirmados</strong><div class="split"><span class="chip">${st.nao} não</span><span class="chip">${st.analise} em análise</span></div><div class="sub">Confirmação da base: ${pc(confirmRate)}</div></div>
  <div class="metric ${pending?'orange':'green'}"><small>Fechamento 2027</small><strong>${complete} / ${cl.length}</strong><div class="sub">${pc(coverage)} das combinações com Matrícula + Mensalidade preenchidas · ${pending} pendentes</div></div>
  <div class="metric teal"><small>Mensalidades contratadas 2027</small><strong>${masked(mensal2027)}</strong><div class="sub">Soma das mensalidades negociadas das matrículas 2027</div></div>
  <div class="metric blue"><small>Matrículas financeiras 2027</small><strong>${masked(mat2027)}</strong><div class="sub">Soma dos valores de matrícula vinculados aos alunos 2027</div></div>
  <div class="metric ${enroll.length?'green':'orange'}"><small>Turmas com matrícula 2027</small><strong>${dist.length}</strong><div class="sub">Distribuição baseada na matrícula 2027, sem alterar o histórico de 2026</div></div>
 </div>
 <div class="dash-row"><div class="dash-card"><h3>Alunos matriculados por turma — 2027</h3><p>Acompanhamento da formação das turmas.</p><div class="progress-list">${dist.length?dist.map(([t,c])=>`<div class="progress-item"><b>${safe(t)}</b><span>${c} aluno${c===1?'':'s'}</span><div class="bar"><span style="width:${Math.max(5,c/max*100)}%"></span></div></div>`).join(''):'<div class="mini">Ainda não há matrículas 2027 para distribuir por turma.</div>'}</div></div>
 <div class="dash-card"><h3>Situação da construção de 2027</h3><p>Pontos que precisam de acompanhamento da direção.</p><div class="status-list"><div class="status-item"><div><b>Fechamento financeiro</b><br><span>Matrícula + mensalidade por condição</span></div><strong>${pending?pending+' pendentes':'Completo'}</strong></div><div class="status-item"><div><b>Decisão das famílias</b><br><span>Alunos ainda em análise</span></div><strong>${st.analise}</strong></div><div class="status-item"><div><b>Rematrículas concluídas</b><br><span>Veteranos já vinculados a 2027</span></div><strong>${veteranos}</strong></div><div class="status-item"><div><b>Novos alunos</b><br><span>Cadastros 2027 identificados como novatos</span></div><strong>${novatos}</strong></div></div></div></div>
 <div class="dash-note"><b>Privacidade:</b> use “Ocultar valores” sempre que a tela estiver visível para terceiros. A opção esconde os indicadores monetários deste dashboard e fica lembrada neste navegador.</div>`;
 let dp=q('#dashPrivacy');if(dp)dp.onclick=()=>{HIDE=!HIDE;localStorage.setItem(PRIV_KEY,HIDE?'1':'0');setPrivacyButton();renderDashboard()};setPrivacyButton();}
R.dash=renderDashboard;
ensureTopButton();
if(active==='dash'&&S)renderDashboard();
})();