(()=>{
if(window.__auroraFechamentoV10)return;window.__auroraFechamentoV10=true;
const CLOSE_API='https://oyuprxoqhhnpcnxgaokj.supabase.co/functions/v1/aurora-fechamento';
const VET_API10='https://oyuprxoqhhnpcnxgaokj.supabase.co/functions/v1/aurora-veteran';
let CLOSE={rows:[],loaded:false,dirty:new Set()};
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const nv=v=>v===null||v===undefined||v===''||Number.isNaN(Number(v))?null:Number(v);
const val=s=>q(s)?.value??'', chk=s=>!!q(s)?.checked;
const br=v=>nv(v)===null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const sty=document.createElement('style');sty.textContent=`
.closing-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;margin:18px 0 10px}.closing-note{background:#effcf9;border:1px solid #b7eee5;border-radius:13px;padding:12px 14px;color:#0f5d57;font-size:12px;line-height:1.5}.closing-tools{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin:12px 0}.closing-groups{display:grid;gap:13px}.closing-group{background:#fff;border:1px solid var(--l);border-radius:15px;overflow:hidden}.closing-group h3{margin:0;padding:12px 14px;background:#f4f7fb;font-size:15px}.closing-row{display:grid;grid-template-columns:minmax(220px,1.7fr) minmax(150px,1fr) 150px 150px 110px;gap:10px;align-items:center;padding:10px 14px;border-top:1px solid #edf2f7}.closing-row .mod b{display:block;font-size:12px}.closing-row .mod span{display:block;font-size:10px;color:var(--m);margin-top:2px}.closing-row label{font-size:9px;font-weight:900;text-transform:uppercase;color:var(--m);display:block;margin-bottom:4px}.closing-row input{font-size:13px;text-align:right}.closing-state{font-size:10px;font-weight:800;padding:5px 8px;border-radius:999px;background:#f1f5f9;text-align:center}.closing-state.ok{background:#dcfce7;color:#166534}.closing-state.wait{background:#fff7ed;color:#9a3412}.closing-savebar{position:sticky;bottom:10px;display:flex;justify-content:flex-end;gap:8px;margin-top:12px;padding:10px;background:#f4f7fbe8;backdrop-filter:blur(6px);border:1px solid var(--l);border-radius:12px;z-index:4}.base-closing{border:1px solid #a7e5da;background:#f0fdfa;border-radius:14px;padding:14px}.base-closing-grid{display:grid;grid-template-columns:1.35fr 1fr 1fr;gap:10px}.base-closing .lbl{font-size:9px;font-weight:900;text-transform:uppercase;color:var(--m)}.base-closing .big{font-size:17px;font-weight:900;margin-top:4px}.base-closing .sub{font-size:10px;color:var(--m);margin-top:4px}.base-alert{margin-top:10px;padding:9px 11px;border-radius:10px;font-size:11px}.base-alert.ok{background:#dcfce7;color:#166534}.base-alert.wait{background:#fff7ed;color:#9a3412}.billing-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}
@media(max-width:1050px){.closing-row{grid-template-columns:1.4fr 1fr 1fr 1fr}.closing-row .statecol{grid-column:2/-1}.base-closing-grid,.billing-grid{grid-template-columns:1fr 1fr}}
@media(max-width:650px){.closing-tools,.closing-row,.base-closing-grid,.billing-grid{grid-template-columns:1fr}.closing-row .statecol{grid-column:auto}.closing-savebar{position:static}}
`;document.head.appendChild(sty);

async function closeApi(action,x={}){let r=await fetch(CLOSE_API,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action,...x}),cache:'no-store'}),d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'fechamento_api_failed');return d}
async function loadClose(force=false){if(CLOSE.loaded&&!force)return CLOSE.rows;let d=await closeApi('list',{ano:2027});CLOSE.rows=d.rows||[];CLOSE.loaded=true;return CLOSE.rows}
function closingStatus(r){return nv(r.valor_matricula)!==null&&nv(r.valor_mensalidade)!==null}
function closeRow(r){let ok=closingStatus(r);return `<div class="closing-row" data-close="${r.id}"><div class="mod"><b>${esc(r.modalidade)}</b><span>${esc(r.condicao)}</span></div><div><label>Condição</label><div>${esc(r.condicao)}</div></div><div><label>Matrícula 2027</label><input class="c-mat" type="number" step=".01" min="0" value="${r.valor_matricula??''}"></div><div><label>Mensalidade 2027</label><input class="c-men" type="number" step=".01" min="0" value="${r.valor_mensalidade??''}"></div><div class="statecol"><span class="closing-state ${ok?'ok':'wait'}">${ok?'Completo':'A preencher'}</span></div></div>`}
async function renderClosing(){let host=q('#fees');host.innerHTML=sec('Fechamento 2027','Base oficial usada automaticamente pela Secretaria ao matricular ou rematricular um aluno.')+'<div class="card">Carregando fechamento...</div>';try{await loadClose();let turmas=[...new Set(CLOSE.rows.map(r=>r.turma))].sort((a,b)=>a.localeCompare(b,'pt-BR'));host.innerHTML=sec('Fechamento 2027','Matrícula + mensalidade por turma, modalidade e condição.')+`<div class="closing-note"><b>Modelo igual ao Cora Gestão:</b> nesta tela entram somente os valores-base de <b>Matrícula</b> e <b>Mensalidade</b>. Produtos, farda, alimentação, esportes e outros serviços ficam fora do Fechamento.</div><div class="closing-tools"><input id="cSearch" placeholder="Buscar modalidade"><select id="cTurma"><option value="">Todas as turmas</option>${turmas.map(t=>`<option>${esc(t)}</option>`).join('')}</select><button id="cSave" class="btn">Salvar fechamento</button></div><div id="cGroups" class="closing-groups"></div><div class="closing-savebar"><span class="mini" id="cDirty">Nenhuma alteração pendente</span><button id="cSaveBottom" class="btn">Salvar alterações</button></div>`;drawClosing();q('#cSearch').oninput=drawClosing;q('#cTurma').onchange=drawClosing;q('#cSave').onclick=saveClosing;q('#cSaveBottom').onclick=saveClosing}catch(e){host.innerHTML=sec('Fechamento 2027','Base oficial da matrícula.')+`<div class="discount-box warnx">Não foi possível carregar o fechamento: ${esc(e.message)}</div>`}}
function drawClosing(){let term=(q('#cSearch')?.value||'').toLowerCase(),tur=q('#cTurma')?.value||'',rows=CLOSE.rows.filter(r=>(!tur||r.turma===tur)&&(!term||(`${r.turma} ${r.modalidade} ${r.condicao}`).toLowerCase().includes(term))),groups={};for(const r of rows)(groups[r.turma]??=[]).push(r);q('#cGroups').innerHTML=Object.entries(groups).map(([t,rs])=>`<section class="closing-group"><h3>${esc(t)}</h3>${rs.map(closeRow).join('')}</section>`).join('')||'<div class="card">Nenhuma modalidade encontrada.</div>';qa('[data-close] input').forEach(i=>i.oninput=()=>{let row=i.closest('[data-close]'),id=row.dataset.close,r=CLOSE.rows.find(x=>x.id===id);if(!r)return;r.valor_matricula=nv(row.querySelector('.c-mat').value);r.valor_mensalidade=nv(row.querySelector('.c-men').value);CLOSE.dirty.add(id);let ok=closingStatus(r),s=row.querySelector('.closing-state');s.className='closing-state '+(ok?'ok':'wait');s.textContent=ok?'Completo':'A preencher';q('#cDirty').textContent=`${CLOSE.dirty.size} alteração(ões) pendente(s)`})}
async function saveClosing(){if(!CLOSE.dirty.size)return toast('Nenhuma alteração para salvar.');let btn=q('#cSaveBottom');if(btn){btn.disabled=true;btn.textContent='Salvando...'}try{let rows=CLOSE.rows.filter(r=>CLOSE.dirty.has(r.id)).map(r=>({id:r.id,ano:2027,turma:r.turma,modalidade:r.modalidade,condicao:r.condicao,valorMatricula:r.valor_matricula,valorMensalidade:r.valor_mensalidade,status:closingStatus(r)?'definido':'rascunho',observacao:r.observacao||'',ativo:r.ativo!==false}));let d=await closeApi('save',{rows});V=d.version||V;CLOSE.dirty.clear();q('#cDirty').textContent='Fechamento salvo na nuvem';toast('✓ Fechamento 2027 salvo');}catch(e){toast('Erro ao salvar fechamento: '+e.message,true)}finally{if(btn){btn.disabled=false;btn.textContent='Salvar alterações'}}}
function matchRate(){let turma=val('#raTurma'),mod=val('#raModalidade'),cond=val('#rfCondicao');return CLOSE.rows.find(r=>r.turma===turma&&r.modalidade===mod&&r.condicao===cond&&r.ativo!==false)||null}
function fillBase(){let r=matchRate(),mat=q('#rfMat'),tab=q('#rfTabela'),neg=q('#rfNeg'),info=q('#rfBaseInfo');if(mat)mat.value=r?.valor_matricula??'';if(tab)tab.value=r?.valor_mensalidade??'';if(neg)neg.value=r?.valor_mensalidade??'';if(info){let ok=r&&closingStatus(r);info.className='base-alert '+(ok?'ok':'wait');info.innerHTML=ok?`✓ Base encontrada no Fechamento: matrícula <b>${br(r.valor_matricula)}</b> + mensalidade <b>${br(r.valor_mensalidade)}</b>.`:'Preencha esta combinação no <b>Fechamento 2027</b> antes de concluir a matrícula.'}}
async function setupFinance(){await loadClose();let old=q('#rfMat')?.closest('.reg-section');if(!old)return;let conds=[...new Set(CLOSE.rows.map(r=>r.condicao))];old.innerHTML=`<h3>7. Financeiro 2027</h3><p>Valores automáticos do Fechamento. Nesta etapa a Secretaria não cria preço novo.</p><div class="base-closing"><div class="base-closing-grid"><div class="field"><label>Condição *</label><select id="rfCondicao" required>${conds.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div><div class="lbl">Matrícula 2027</div><div class="big" id="rfMatView">—</div></div><div><div class="lbl">Mensalidade 2027</div><div class="big" id="rfMenView">—</div></div></div><input id="rfMat" type="hidden"><input id="rfTabela" type="hidden"><input id="rfNeg" type="hidden"><input id="rfExtras" type="hidden" value="0"><div id="rfBaseInfo" class="base-alert wait"></div></div><div class="billing-grid"><div class="field"><label>Dia do vencimento</label><input id="rfVenc" type="number" min="1" max="31"></div><div class="field"><label>Forma de pagamento</label><select id="rfForma"><option value="">A definir</option><option>PIX</option><option>Boleto</option><option>Cartão</option><option>Dinheiro</option><option>Transferência</option></select></div><div class="field"><label>Status financeiro</label><select id="rfStatus"><option value="a_definir">A definir</option><option value="regular">Regular</option><option value="negociado">Negociado</option><option value="bolsista">Bolsista</option></select></div><div class="field"><label>Observação financeira</label><input id="rfObs"></div></div>`;
 const redraw=()=>{fillBase();let r=matchRate();q('#rfMatView').textContent=br(r?.valor_matricula);q('#rfMenView').textContent=br(r?.valor_mensalidade)};
 q('#rfCondicao').onchange=redraw;let t=q('#raTurma'),m=q('#raModalidade');if(t)t.addEventListener('change',()=>setTimeout(redraw,40));if(m)m.addEventListener('change',()=>setTimeout(redraw,40));redraw();
 let form=q('#regForm');if(form)form.onsubmit=submitClosingRegistration;
}
function buildPayload10(){let g1={nome:val('#rg1Nome'),parentesco:val('#rg1Parentesco'),cpf:val('#rg1Cpf'),rg:val('#rg1Rg'),whatsapp:val('#rg1Whatsapp'),telefone:val('#rg1Telefone'),email:val('#rg1Email'),profissao:val('#rg1Profissao'),responsavelFinanceiro:chk('#rg1Financeiro'),autorizadoRetirada:chk('#rg1Retirada'),contatoEmergencia:chk('#rg1Emergencia'),moraComAluno:chk('#rg1Mora'),principal:true},g2={nome:val('#rg2Nome'),parentesco:val('#rg2Parentesco'),cpf:val('#rg2Cpf'),rg:val('#rg2Rg'),whatsapp:val('#rg2Whatsapp'),telefone:val('#rg2Telefone'),email:val('#rg2Email'),profissao:val('#rg2Profissao'),responsavelFinanceiro:chk('#rg2Financeiro'),autorizadoRetirada:chk('#rg2Retirada'),contatoEmergencia:chk('#rg2Emergencia'),moraComAluno:chk('#rg2Mora'),principal:false};return{student:{aluno:val('#raNome'),turma:val('#raTurma'),turno:val('#raTurno'),modalidade:val('#raModalidade'),responsavel:g1.nome},profile:{nomePreferencial:val('#raPreferido'),dataNascimento:val('#raNasc'),cpf:val('#raCpf'),rg:val('#raRg'),certidaoNascimento:val('#raCertidao'),nacionalidade:val('#raNacionalidade'),naturalidade:val('#raNaturalidade'),ufNascimento:val('#raUfNasc'),escolaAnterior:val('#raEscolaAnterior'),cep:val('#raCep'),endereco:val('#raEndereco'),numero:val('#raNumero'),complemento:val('#raComplemento'),bairro:val('#raBairro'),cidade:val('#raCidade'),uf:val('#raUf'),contatoEmergenciaNome:val('#raEmergNome'),contatoEmergenciaParentesco:val('#raEmergParentesco'),contatoEmergenciaTelefone:val('#raEmergTelefone'),alergias:val('#raAlergias'),medicacao:val('#raMedicacao'),observacaoSaude:val('#raSaude'),apoioEspecial:val('#raApoio'),autorizacaoImagem:chk('#raImg'),autorizacaoSaida:chk('#raSaida'),autorizacaoAtendimentoEmergencial:chk('#raEmergCare'),autorizadosRetirada:val('#raAutorizados'),observacaoSecretaria:val('#raObsSec')},guardians:[g1,g2],enrollment:{anoLetivo:val('#raAno')||2027,tipoAluno:val('#raTipo')||'Novato',dataMatricula:val('#raDataMat'),dataInicio:val('#raDataInicio'),status:val('#raStatus'),origemAtendimento:val('#raOrigem')||'secretaria',atendente:val('#raAtendente'),whatsapp:g1.whatsapp,telefone:g1.telefone,email:g1.email,valorMatricula:val('#rfMat'),mensalidadeTabela:val('#rfTabela'),mensalidadeNegociada:val('#rfNeg'),servicosExtras:0,diaVencimento:val('#rfVenc'),formaPagamento:val('#rfForma'),statusFinanceiro:val('#rfStatus'),observacaoFinanceira:val('#rfObs')}}}
async function vetCall(action,x={}){let r=await fetch(VET_API10,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action,...x}),cache:'no-store'}),d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'veteran_api_failed');return d}
async function submitClosingRegistration(e){e.preventDefault();let form=q('#regForm'),btn=q('#regSave'),rate=matchRate();if(!rate||!closingStatus(rate))return toast('Preencha Matrícula e Mensalidade desta combinação no Fechamento 2027.',true);btn.disabled=true;btn.textContent=form.dataset.veteranId?'Salvando rematrícula...':'Salvando matrícula...';try{let payload=buildPayload10(),studentId,matricula;if(form.dataset.veteranId){studentId=form.dataset.veteranId;let r=await vetCall('reenroll',{studentId,payload});matricula=r.matricula;V=r.version||V}else{let r=await api('registerStudent',{payload});studentId=r.studentId;matricula=r.matricula;V=r.version||V}await closeApi('linkEnrollment',{studentId,rateId:rate.id});let d=await api('get');S=d.state;V=d.version;toast(`✓ ${payload.enrollment.tipoAluno==='Veterano'?'Rematrícula':'Matrícula'} ${matricula} criada com base no Fechamento`);show('records')}catch(x){toast('Não foi possível concluir: '+x.message,true)}finally{btn.disabled=false;btn.textContent=form.dataset.veteranId?'Salvar rematrícula 2027':'Salvar cadastro e gerar matrícula'}}
const oldReg=R.register;R.register=()=>{oldReg();setTimeout(()=>setupFinance().catch(e=>toast('Erro ao carregar Fechamento: '+e.message,true)),180)};
R.fees=renderClosing;
let nav=q('#nav [data-v="fees"]');if(nav)nav.textContent='R$ Fechamento 2027';
})();