(()=>{
if(window.__auroraRelatoriosV22)return;window.__auroraRelatoriosV22=true;
const CLOSE_API='https://oyuprxoqhhnpcnxgaokj.supabase.co/functions/v1/aurora-fechamento';
let LAST=null;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const num=v=>v===null||v===undefined||v===''||Number.isNaN(Number(v))?null:Number(v);
const money=v=>num(v)===null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const perc=v=>num(v)===null?'—':(Number(v)*100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
const text=v=>String(v??'');
const safe=v=>text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateBR=v=>{if(!v)return '—';const d=new Date((String(v).length===10?v+'T12:00:00':v));return Number.isNaN(d.getTime())?text(v):d.toLocaleDateString('pt-BR')};
const today=()=>new Date().toISOString().slice(0,10);
const labelStatus=v=>text(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())||'—';
const style=document.createElement('style');style.textContent=`
.report-builder{background:#fff;border:1px solid var(--l);border-radius:16px;padding:16px;margin-top:12px}.report-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px}.report-options{display:flex;gap:9px;flex-wrap:wrap;margin:12px 0}.report-check{display:flex;gap:7px;align-items:center;border:1px solid var(--l);background:#f8fafc;border-radius:10px;padding:8px 10px;font-size:11px}.report-check input{width:auto}.report-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.report-hint{font-size:10px;color:var(--m);margin-left:auto}.report-preview{margin-top:14px;background:#fff;border:1px solid var(--l);border-radius:16px;overflow:hidden}.report-preview-head{padding:15px 16px;border-bottom:1px solid var(--l);display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.report-preview-head h3{margin:0;font-size:18px}.report-preview-head p{margin:4px 0 0;color:var(--m);font-size:11px}.report-meta{font-size:10px;color:var(--m);text-align:right}.report-tablebox{overflow:auto}.report-table{width:100%;border-collapse:collapse;min-width:800px}.report-table th{background:#f4f7fb;padding:9px;font-size:9px;text-align:left;white-space:nowrap}.report-table td{padding:9px;border-top:1px solid #edf1f6;font-size:10px;vertical-align:top}.report-table .r-money{text-align:right;white-space:nowrap}.report-empty{padding:28px;text-align:center;color:var(--m);font-size:12px}.report-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;padding:14px}.report-summary>div{background:#f8fafc;border:1px solid var(--l);border-radius:12px;padding:11px}.report-summary small{display:block;color:var(--m);font-size:9px;text-transform:uppercase;font-weight:800}.report-summary b{display:block;font-size:17px;margin-top:4px}.report-loading{padding:26px;text-align:center;color:var(--m)}
@media(max-width:1000px){.report-grid,.report-summary{grid-template-columns:1fr 1fr}}@media(max-width:600px){.report-grid,.report-summary{grid-template-columns:1fr}.report-preview-head{display:block}.report-meta{text-align:left;margin-top:8px}.report-hint{width:100%;margin-left:0}}
`;document.head.appendChild(style);

function installNav(){
 const nav=q('#nav');if(!nav||nav.querySelector('[data-v="reports"]'))return;
 const base=[...nav.querySelectorAll('.nav-group')].find(x=>x.textContent.trim().toLowerCase()==='base');
 const group=document.createElement('div');group.className='nav-group';group.textContent='Relatórios';
 const btn=document.createElement('button');btn.dataset.v='reports';btn.textContent='▣ Relatórios';
 if(base){nav.insertBefore(group,base);nav.insertBefore(btn,base)}else{nav.append(group,btn)}
 const db=q('#db');if(db&&!q('#reports')){const el=document.createElement('section');el.id='reports';el.className='view';db.parentNode.insertBefore(el,db)}
}
function turmaOptions(){let a=[];try{a=turmaList()}catch{}return ['<option value="">Todas as turmas</option>',...a.map(x=>`<option value="${safe(x)}">${safe(x)}</option>`)].join('')}
function renderReports(){
 installNav();const host=q('#reports');if(!host)return;
 host.innerHTML=sec('Relatórios','Escolha o relatório, filtros e informações que deseja incluir. A geração sempre busca a versão mais recente da nuvem.')+`<div class="report-builder">
 <div class="report-grid">
  <div class="field"><label>Tipo de relatório</label><select id="rpType"><option value="gestao">Gestão geral / Resumo executivo</option><option value="alunos">Alunos por turma</option><option value="cadastros">Cadastros da Secretaria</option><option value="matriculas">Matrículas e Rematrículas 2027</option><option value="financeiro">Financeiro 2026 × 2027 por família</option><option value="fechamento">Fechamento 2027</option><option value="produtos">Serviços e Produtos</option><option value="frequencia">Frequência</option><option value="assinaturas">Lista de Assinaturas</option><option value="pendencias">Pendências 2027</option></select></div>
  <div class="field"><label>Ano</label><select id="rpYear"><option value="2027">2027</option><option value="2026">2026</option></select></div>
  <div class="field"><label>Turma</label><select id="rpTurma">${turmaOptions()}</select></div>
  <div class="field"><label>Data</label><input id="rpDate" type="date" value="${today()}"></div>
 </div>
 <div class="report-grid" style="margin-top:10px">
  <div class="field"><label>Status / Situação</label><select id="rpStatus"><option value="">Todos</option><option value="matriculado">Matriculado</option><option value="pre_matricula">Pré-matrícula</option><option value="regular">Regular</option><option value="negociado">Negociado</option><option value="a_definir">A definir</option><option value="sim">Serei 2027: Sim</option><option value="nao">Serei 2027: Não</option><option value="em_analise">Serei 2027: Em análise</option></select></div>
  <div class="field"><label>Título personalizado</label><input id="rpTitle" placeholder="Ex.: Reunião de pais"></div><div></div><div></div>
 </div>
 <div class="report-options"><label class="report-check"><input id="rpValues" type="checkbox" checked> Incluir valores financeiros</label><label class="report-check"><input id="rpContact" type="checkbox" checked> Incluir responsável/contato</label><label class="report-check"><input id="rpObs" type="checkbox"> Incluir observações</label></div>
 <div class="report-actions"><button id="rpGenerate" class="btn">Atualizar e gerar relatório</button><button id="rpPrint" class="btn ghost" disabled>Imprimir / Salvar PDF</button><button id="rpCsv" class="btn ghost" disabled>Baixar CSV</button><span id="rpFresh" class="report-hint">Nenhum relatório gerado nesta sessão.</span></div>
 </div><div id="rpPreview" class="report-preview"><div class="report-empty">Selecione as opções e clique em <b>Atualizar e gerar relatório</b>.</div></div>`;
 q('#rpGenerate').onclick=generate;q('#rpPrint').onclick=printLast;q('#rpCsv').onclick=csvLast;q('#rpType').onchange=adaptControls;adaptControls();
}
function adaptControls(){const t=q('#rpType')?.value||'';const date=q('#rpDate'),year=q('#rpYear'),status=q('#rpStatus'),title=q('#rpTitle');if(date)date.disabled=!['frequencia','assinaturas'].includes(t);if(year)year.disabled=['fechamento','produtos','frequencia','assinaturas','pendencias','matriculas'].includes(t);if(status)status.disabled=['gestao','fechamento','produtos','frequencia','assinaturas'].includes(t);if(title)title.disabled=t!=='assinaturas'}
async function closingRows(){const r=await fetch(CLOSE_API,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action:'list',ano:2027}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'fechamento_indisponivel');return d.rows||[]}
async function refreshCloud(){const d=await api('get');S=d.state;V=d.version||V;const ve=q('#ver');if(ve)ve.textContent='versão '+V;return d}
function filters(){return{type:q('#rpType').value,year:Number(q('#rpYear').value||2027),turma:q('#rpTurma').value,status:q('#rpStatus').value,date:q('#rpDate').value||today(),title:q('#rpTitle').value.trim(),values:q('#rpValues').checked,contact:q('#rpContact').checked,obs:q('#rpObs').checked}}
function col(key,label,kind='text'){return{key,label,kind}}
function make(title,subtitle,columns,rows,summary=[],note=''){return{title,subtitle,columns,rows,summary,note,generatedAt:new Date().toISOString()}}
function latestEnrollment(enrollments,id,year=2027){return enrollments.filter(e=>e.student_id===id&&Number(e.ano_letivo)===year).sort((a,b)=>new Date(b.updated_at||b.created_at||0)-new Date(a.updated_at||a.created_at||0))[0]||null}
function guardianFor(guardians,id){return guardians.find(g=>g.student_id===id&&g.principal)||guardians.find(g=>g.student_id===id)||null}
function filterRows(rows,f,fields=['turma']){return rows.filter(r=>!f.turma||fields.some(k=>text(r[k]).toLowerCase()===f.turma.toLowerCase()))}
function finance2026(s){const table=num(s.valorOficial2026),paid=num(s.base2026),disc=table!==null&&paid!==null?table-paid:null;return{table,paid,disc,pct:table&&disc!==null?disc/table:null}}
async function build(f){
 let secData={profiles:[],guardians:[],enrollments:[]};
 if(['gestao','alunos','cadastros','matriculas','financeiro','assinaturas','pendencias'].includes(f.type)){try{const d=await api('secretary');secData={profiles:d.profiles||[],guardians:d.guardians||[],enrollments:d.enrollments||[]}}catch{}}
 if(f.type==='gestao')return reportGestao(f,secData,await closingRows());
 if(f.type==='alunos')return reportAlunos(f,secData);
 if(f.type==='cadastros')return reportCadastros(f,secData);
 if(f.type==='matriculas')return reportMatriculas(f,secData);
 if(f.type==='financeiro')return reportFinanceiro(f,secData);
 if(f.type==='fechamento')return reportFechamento(f,await closingRows());
 if(f.type==='produtos')return reportProdutos(f);
 if(f.type==='frequencia')return reportFrequencia(f);
 if(f.type==='assinaturas')return reportAssinaturas(f,secData);
 if(f.type==='pendencias')return reportPendencias(f,secData,await closingRows());
 throw new Error('Tipo de relatório inválido');
}
function reportGestao(f,secData,close){
 const students=S?.students||[],ens=secData.enrollments.filter(e=>Number(e.ano_letivo)===2027),revenue=students.reduce((a,s)=>a+(num(s.totalPago2026)||0),0),yes=students.filter(s=>s.serei2027==='sim').length,no=students.filter(s=>s.serei2027==='nao').length,analysis=students.filter(s=>!s.serei2027||s.serei2027==='em_analise').length,complete=close.filter(r=>num(r.valor_matricula)!==null&&num(r.valor_mensalidade)!==null).length;
 let rows=(S?.classes||[]).map(c=>({turma:c.turma,alunos:c.linhas,receita:c.calculado2026,status:c.status||'—'}));if(f.turma)rows=rows.filter(r=>r.turma===f.turma);
 const cols=[col('turma','Turma'),col('alunos','Alunos')];if(f.values)cols.push(col('receita','Receita 2026','money'));cols.push(col('status','Status'));
 const summary=[['Alunos base 2026',students.length],['Matrículas 2027',ens.length],['Serei 2027 · Sim',yes],['Em análise',analysis],['Fechamento completo',`${complete}/${close.length}`]];if(f.values)summary.splice(1,0,['Receita 2026',money(revenue)]);if(no)summary.push(['Serei 2027 · Não',no]);
 return make('Relatório de Gestão Geral','Resumo executivo da construção 2026 → 2027.',cols,rows,summary,'Dados atualizados da nuvem no momento da geração.');
}
function reportAlunos(f,secData){
 let rows=[];
 if(f.year===2026){rows=(S?.students||[]).map(s=>({aluno:s.aluno,turma:s.turma,modalidade:s.servico,turno:s.turno||'',responsavel:s.responsavel,situacao:labelStatus(s.serei2027),observacao:s.observacao||''}))}
 else{rows=secData.enrollments.filter(e=>Number(e.ano_letivo)===2027).map(e=>({aluno:e.aluno,turma:e.serie||e.turma||'',modalidade:e.modalidade||'',turno:e.turno||'',responsavel:e.responsavel||'',situacao:labelStatus(e.status),observacao:e.observacao||''}))}
 if(f.turma)rows=rows.filter(r=>r.turma===f.turma);if(f.status)rows=rows.filter(r=>text(r.situacao).toLowerCase().includes(f.status.replaceAll('_',' ')));
 let cols=[col('aluno','Aluno'),col('turma','Turma'),col('modalidade','Modalidade'),col('turno','Turno')];if(f.contact)cols.push(col('responsavel','Responsável'));cols.push(col('situacao','Situação'));if(f.obs)cols.push(col('observacao','Observação'));
 rows.sort((a,b)=>a.turma.localeCompare(b.turma,'pt-BR')||a.aluno.localeCompare(b.aluno,'pt-BR'));
 return make(`Alunos por turma · ${f.year}`,f.turma?`Turma: ${f.turma}`:'Todas as turmas',cols,rows,[['Registros',rows.length]]);
}
function reportCadastros(f,secData){
 const profileMap=new Map(secData.profiles.map(p=>[p.student_id,p]));let rows=(S?.students||[]).map(s=>{const p=profileMap.get(s.id)||{},g=guardianFor(secData.guardians,s.id)||{},e=latestEnrollment(secData.enrollments,s.id,2027);return{matricula:p.matricula||'',aluno:s.aluno,turma:e?.serie||s.turma,turno:e?.turno||s.turno||'',modalidade:e?.modalidade||s.servico,responsavel:g.nome||e?.responsavel||s.responsavel,whatsapp:g.whatsapp||e?.whatsapp||'',email:g.email||e?.email||'',status:p.status_academico||e?.status||'base 2026',observacao:p.observacao_secretaria||e?.observacao||s.observacao||''}});
 if(f.turma)rows=rows.filter(r=>r.turma===f.turma);if(f.status)rows=rows.filter(r=>text(r.status).toLowerCase().includes(f.status.replaceAll('_',' ')));
 let cols=[col('matricula','Matrícula'),col('aluno','Aluno'),col('turma','Turma'),col('turno','Turno'),col('modalidade','Modalidade')];if(f.contact)cols.push(col('responsavel','Responsável'),col('whatsapp','WhatsApp'),col('email','E-mail'));cols.push(col('status','Status'));if(f.obs)cols.push(col('observacao','Observação'));
 return make('Cadastros da Secretaria','Cadastro central disponível para operação escolar.',cols,rows,[['Cadastros listados',rows.length]],'Campos não existentes na base histórica permanecem em branco até a atualização cadastral.');
}
function reportMatriculas(f,secData){
 let rows=secData.enrollments.filter(e=>Number(e.ano_letivo)===2027).map(e=>({data:e.data_matricula||e.data_atendimento,aluno:e.aluno,tipo:e.tipo_aluno,turma:e.serie||'',turno:e.turno||'',modalidade:e.modalidade||'',condicao:e.condicao_financeira||'',responsavel:e.responsavel||'',matricula:e.valor_matricula,mensalidade:e.mensalidade_negociada??e.mensalidade_tabela,status:e.status,financeiro:e.status_financeiro||'',observacao:e.observacao||e.observacao_financeira||''}));
 if(f.turma)rows=rows.filter(r=>r.turma===f.turma);if(f.status)rows=rows.filter(r=>[r.status,r.financeiro].some(x=>text(x)===f.status));
 let cols=[col('data','Data','date'),col('aluno','Aluno'),col('tipo','Tipo'),col('turma','Turma'),col('turno','Turno'),col('modalidade','Modalidade'),col('condicao','Condição')];if(f.contact)cols.push(col('responsavel','Responsável'));if(f.values)cols.push(col('matricula','Matrícula','money'),col('mensalidade','Mensalidade','money'));cols.push(col('status','Status'),col('financeiro','Financeiro'));if(f.obs)cols.push(col('observacao','Observação'));
 const nov=rows.filter(r=>text(r.tipo).toLowerCase().includes('nov')).length,vet=rows.filter(r=>text(r.tipo).toLowerCase().includes('vet')).length;
 return make('Matrículas e Rematrículas 2027',f.turma?`Turma: ${f.turma}`:'Todas as turmas',cols,rows,[['Total',rows.length],['Novatos',nov],['Veteranos',vet]]);
}
function reportFinanceiro(f,secData){
 let rows=(S?.students||[]).map(s=>{const z=finance2026(s),e=latestEnrollment(secData.enrollments,s.id,2027),v27=num(e?.mensalidade_negociada)??num(s.valor2027Cobrado);return{aluno:s.aluno,turma2026:s.turma,modalidade:s.servico,responsavel:s.responsavel,tabela2026:z.table,pago2026:z.paid,desconto2026:z.disc,descontoPct:z.pct,turma2027:e?.serie||'',tabela2027:num(e?.mensalidade_tabela),cobrado2027:v27,reajuste:z.paid&&v27!==null?(v27-z.paid)/z.paid:null,status:e?.status_financeiro||s.status2027||'',observacao:e?.observacao_financeira||s.observacao2027||s.observacao||''}});
 if(f.turma)rows=rows.filter(r=>r.turma2026===f.turma||r.turma2027===f.turma);if(f.status)rows=rows.filter(r=>text(r.status)===f.status);
 let cols=[col('aluno','Aluno'),col('turma2026','Turma 2026'),col('modalidade','Modalidade')];if(f.contact)cols.push(col('responsavel','Responsável'));if(f.values)cols.push(col('tabela2026','Tabela 2026','money'),col('pago2026','Pago família 2026','money'),col('desconto2026','Desconto R$','money'),col('descontoPct','Desconto %','percent'),col('tabela2027','Tabela 2027','money'),col('cobrado2027','Cobrado 2027','money'),col('reajuste','Reajuste família','percent'));cols.push(col('turma2027','Turma 2027'),col('status','Situação'));if(f.obs)cols.push(col('observacao','Observação'));
 return make('Financeiro 2026 × 2027 por família','Comparação individual entre o praticado em 2026 e o definido/negociado para 2027.',cols,rows,[['Famílias/alunos',rows.length]],'Quando não existe tabela oficial ou matrícula 2027, o campo permanece em branco.');
}
function reportFechamento(f,close){let rows=close.map(r=>({turma:r.turma,modalidade:r.modalidade,condicao:r.condicao,matricula:r.valor_matricula,mensalidade:r.valor_mensalidade,status:(num(r.valor_matricula)!==null&&num(r.valor_mensalidade)!==null)?'Completo':'A preencher',observacao:r.observacao||''}));if(f.turma)rows=rows.filter(r=>r.turma===f.turma);const complete=rows.filter(r=>r.status==='Completo').length;let cols=[col('turma','Turma'),col('modalidade','Modalidade'),col('condicao','Condição')];if(f.values)cols.push(col('matricula','Matrícula 2027','money'),col('mensalidade','Mensalidade 2027','money'));cols.push(col('status','Status'));if(f.obs)cols.push(col('observacao','Observação'));return make('Fechamento 2027','Base oficial de Matrícula + Mensalidade usada pela Secretaria.',cols,rows,[['Combinações',rows.length],['Completas',complete],['Pendentes',rows.length-complete]]);}
function reportProdutos(f){let rows=(S?.products||[]).map(p=>({categoria:p.categoria,produto:p.produto,series:p.series,periodicidade:p.periodicidade||'',valor2026:p.valor2026,valor2027:p.valor2027Cobrado,reajuste:p.valor2026&&num(p.valor2027Cobrado)!==null?(p.valor2027Cobrado-p.valor2026)/p.valor2026:p.reajuste2027,status:p.status2027||'',observacao:p.observacao||''}));let cols=[col('categoria','Categoria'),col('produto','Produto'),col('series','Séries'),col('periodicidade','Periodicidade')];if(f.values)cols.push(col('valor2026','Valor 2026','money'),col('valor2027','Valor 2027','money'),col('reajuste','Reajuste','percent'));cols.push(col('status','Status'));if(f.obs)cols.push(col('observacao','Observação'));return make('Serviços e Produtos','Catálogo financeiro separado do Fechamento de matrícula/mensalidade.',cols,rows,[['Produtos/serviços',rows.length]]);}
async function reportFrequencia(f){if(!f.turma)throw new Error('Para frequência, selecione uma turma.');const d=await api('attendanceList',{turma:f.turma,data:f.date});let rows=(d.rows||[]).map(r=>({aluno:r.aluno,matricula:r.matricula||'',turma:r.turma||f.turma,turno:r.turno||'',modalidade:r.servico||r.modalidade||'',status:r.attendance?.status||'—',entrada:r.attendance?.hora_entrada||'',saida:r.attendance?.hora_saida||'',observacao:r.attendance?.observacao||''}));let cols=[col('matricula','Matrícula'),col('aluno','Aluno'),col('turno','Turno'),col('modalidade','Modalidade'),col('status','Status'),col('entrada','Entrada'),col('saida','Saída')];if(f.obs)cols.push(col('observacao','Observação'));return make(`Frequência · ${dateBR(f.date)}`,`Turma: ${f.turma}`,cols,rows,[['Alunos',rows.length],['Presentes',rows.filter(r=>r.status==='presente').length],['Faltas',rows.filter(r=>r.status==='falta').length]]);}
function reportAssinaturas(f,secData){if(!f.turma)throw new Error('Para lista de assinaturas, selecione uma turma.');let ens=secData.enrollments.filter(e=>Number(e.ano_letivo)===2027&&(e.serie===f.turma||e.turma===f.turma)),rows;if(ens.length)rows=ens.map((e,i)=>({ordem:i+1,aluno:e.aluno,responsavel:e.responsavel||'',assinatura:'',observacao:''}));else rows=(S?.students||[]).filter(s=>s.turma===f.turma).map((s,i)=>({ordem:i+1,aluno:s.aluno,responsavel:s.responsavel,assinatura:'',observacao:''}));rows.sort((a,b)=>a.aluno.localeCompare(b.aluno,'pt-BR'));rows.forEach((r,i)=>r.ordem=i+1);let cols=[col('ordem','Nº'),col('aluno','Aluno')];if(f.contact)cols.push(col('responsavel','Responsável'));cols.push(col('assinatura','Assinatura'));if(f.obs)cols.push(col('observacao','Observação'));return make(f.title||'Lista de Assinaturas',`${f.turma} · ${dateBR(f.date)}`,cols,rows,[['Alunos',rows.length]],'Lista pronta para impressão e assinatura manual.');}
function reportPendencias(f,secData,close){let rows=[];for(const s of S?.students||[]){if(!s.serei2027||s.serei2027==='em_analise')rows.push({categoria:'Rematrícula',aluno:s.aluno,turma:s.turma,pendencia:'Serei 2027 em análise',status:'Pendente'});if(num(s.valor2027Cobrado)===null)rows.push({categoria:'Financeiro',aluno:s.aluno,turma:s.turma,pendencia:'Valor cobrado 2027 não definido',status:'Pendente'});}for(const r of close){if(num(r.valor_matricula)===null||num(r.valor_mensalidade)===null)rows.push({categoria:'Fechamento',aluno:r.modalidade,turma:r.turma,pendencia:`${r.condicao}: Matrícula/Mensalidade incompleta`,status:'Pendente'})}for(const e of secData.enrollments.filter(e=>Number(e.ano_letivo)===2027)){if(!e.status_financeiro||e.status_financeiro==='a_definir')rows.push({categoria:'Matrícula 2027',aluno:e.aluno,turma:e.serie||'',pendencia:'Status financeiro a definir',status:'Pendente'})}if(f.turma)rows=rows.filter(r=>r.turma===f.turma);let cols=[col('categoria','Categoria'),col('aluno','Aluno / Item'),col('turma','Turma'),col('pendencia','Pendência'),col('status','Status')];return make('Pendências 2027','Pontos que ainda precisam de conferência ou definição.',cols,rows,[['Pendências',rows.length]]);}
function formatCell(v,kind){if(kind==='money')return money(v);if(kind==='percent')return perc(v);if(kind==='date')return dateBR(v);return text(v)||'—'}
function preview(rep){const box=q('#rpPreview'),summary=rep.summary?.length?`<div class="report-summary">${rep.summary.map(([a,b])=>`<div><small>${safe(a)}</small><b>${safe(b)}</b></div>`).join('')}</div>`:'',head=`<div class="report-preview-head"><div><h3>${safe(rep.title)}</h3><p>${safe(rep.subtitle||'')}</p></div><div class="report-meta">Gerado em ${new Date(rep.generatedAt).toLocaleString('pt-BR')}<br>Versão da nuvem: ${safe(V)}</div></div>`;let body;if(!rep.rows.length)body='<div class="report-empty">Nenhum registro encontrado com os filtros selecionados.</div>';else body=`<div class="report-tablebox"><table class="report-table"><thead><tr>${rep.columns.map(c=>`<th>${safe(c.label)}</th>`).join('')}</tr></thead><tbody>${rep.rows.map(r=>`<tr>${rep.columns.map(c=>`<td class="${c.kind==='money'?'r-money':''}">${safe(formatCell(r[c.key],c.kind))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;box.innerHTML=head+summary+body+(rep.note?`<div class="mini" style="padding:12px 16px;border-top:1px solid var(--l)">${safe(rep.note)}</div>`:'')}
async function generate(){const btn=q('#rpGenerate');btn.disabled=true;btn.textContent='Atualizando dados…';q('#rpPreview').innerHTML='<div class="report-loading">Buscando a versão mais recente da nuvem…</div>';try{await refreshCloud();const f=filters();btn.textContent='Gerando relatório…';LAST=await build(f);preview(LAST);q('#rpPrint').disabled=false;q('#rpCsv').disabled=LAST.rows.length===0;q('#rpFresh').textContent=`Atualizado agora · nuvem v${V} · ${LAST.rows.length} registro(s)`;toast('✓ Relatório atualizado e gerado')}catch(e){LAST=null;q('#rpPreview').innerHTML=`<div class="report-empty">Não foi possível gerar: <b>${safe(e.message)}</b></div>`;q('#rpPrint').disabled=true;q('#rpCsv').disabled=true;toast('Erro ao gerar relatório: '+e.message,true)}finally{btn.disabled=false;btn.textContent='Atualizar e gerar relatório'}}
function logoUrl(){return q('.brand img')?.src||q('.mark img')?.src||new URL('./aurora-logo.webp?v=22',location.href).href}
function printLast(){if(!LAST)return;const rep=LAST,w=open('','_blank');if(!w)return toast('O navegador bloqueou a janela de impressão.',true);const summary=rep.summary?.length?`<div class="sum">${rep.summary.map(([a,b])=>`<div><small>${safe(a)}</small><b>${safe(b)}</b></div>`).join('')}</div>`:'';const rows=rep.rows.length?`<table><thead><tr>${rep.columns.map(c=>`<th>${safe(c.label)}</th>`).join('')}</tr></thead><tbody>${rep.rows.map(r=>`<tr>${rep.columns.map(c=>`<td class="${c.kind==='money'?'money':''}">${safe(formatCell(r[c.key],c.kind))}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p>Nenhum registro encontrado.</p>';w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${safe(rep.title)}</title><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;margin:0;font-size:10px}.head{display:flex;align-items:center;gap:16px;border-bottom:2px solid #0f766e;padding-bottom:10px;margin-bottom:12px}.head img{width:82px;height:62px;object-fit:contain}.head h1{font-size:18px;margin:0}.head p{margin:3px 0;color:#667085}.meta{margin-left:auto;text-align:right;font-size:9px;color:#667085}.sum{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.sum div{border:1px solid #dbe4ee;padding:8px;border-radius:8px}.sum small{display:block;color:#667085;font-size:8px;text-transform:uppercase}.sum b{display:block;margin-top:3px;font-size:13px}table{width:100%;border-collapse:collapse;margin-top:8px}th{background:#eaf5f3;text-align:left;font-size:8px;padding:6px;border:1px solid #cbd5e1}td{padding:6px;border:1px solid #dbe4ee;vertical-align:top}.money{text-align:right;white-space:nowrap}.note{margin-top:10px;color:#667085}.foot{margin-top:16px;padding-top:8px;border-top:1px solid #cbd5e1;text-align:center;color:#667085;font-size:8px}.foot b{color:#b91c1c}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body><div class="head"><img src="${logoUrl()}"><div><h1>Berçário e Creche Escola Aurora</h1><p>${safe(rep.title)}<br>${safe(rep.subtitle||'')}</p></div><div class="meta">Gerado em ${new Date(rep.generatedAt).toLocaleString('pt-BR')}<br>Base nuvem v${safe(V)}</div></div>${summary}${rows}${rep.note?`<div class="note">${safe(rep.note)}</div>`:''}<div class="foot">Berçário e Creche Escola Aurora · Direção Carla Diniz<br><b>Desenvolvido por PDF Solução Educacional</b> · (85) 98416-1882</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
function csvValue(v){const s=text(v).replaceAll('"','""');return `"${s}"`}
function csvLast(){if(!LAST||!LAST.rows.length)return;const lines=[LAST.columns.map(c=>csvValue(c.label)).join(';'),...LAST.rows.map(r=>LAST.columns.map(c=>csvValue(formatCell(r[c.key],c.kind))).join(';'))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(LAST.title||'relatorio-aurora').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
installNav();R.reports=renderReports;
})();