(()=>{
if(window.__auroraVeteranoV9)return;window.__auroraVeteranoV9=true;
const VET_API='https://oyuprxoqhhnpcnxgaokj.supabase.co/functions/v1/aurora-veteran';
const ITEMS_API9='https://oyuprxoqhhnpcnxgaokj.supabase.co/functions/v1/aurora-enrollment-items';
const LOGO='https://aurora-receita-escola.netlify.app/aurora-logo.png';
let VSEC=null;
const q=s=>document.querySelector(s),val=s=>q(s)?.value??'',chk=s=>!!q(s)?.checked;
const nn=v=>v===null||v===undefined||v===''||Number.isNaN(Number(v))?null:Number(v);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const sty=document.createElement('style');sty.textContent=`
.aurora-brand-logo{display:block;object-fit:contain}.brand .aurora-brand-logo{width:94px;height:54px;margin:0 0 8px 2px;filter:drop-shadow(0 3px 8px #0002)}.mark .aurora-brand-logo{width:74px;height:52px}.mark{background:#fff!important;width:88px!important;height:62px!important}.aurora-top-logo{width:118px;height:62px;object-fit:contain;float:right;margin:-4px 0 4px 20px}
.name-field-wrap{position:relative}.vet-suggest{position:absolute;z-index:30;left:0;right:0;top:100%;margin-top:4px;background:#fff;border:1px solid #cfd9e6;border-radius:12px;box-shadow:0 12px 30px #0b1f3622;max-height:280px;overflow:auto;display:none}.vet-suggest.open{display:block}.vet-option{padding:10px 12px;border-bottom:1px solid #edf2f7;cursor:pointer}.vet-option:last-child{border-bottom:0}.vet-option:hover{background:#f0fdfa}.vet-option b{display:block;font-size:13px}.vet-option span{display:block;color:var(--m);font-size:10px;margin-top:3px}.vet-banner{display:none;margin-top:10px;border:1px solid #99e5d8;background:#effcf9;border-radius:12px;padding:12px 13px;color:#0f5d57}.vet-banner.show{display:block}.vet-banner b{font-size:13px}.vet-banner .route{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:5px;font-size:11px}.vet-banner .chip{background:#fff;border:1px solid #b7eee5;border-radius:999px;padding:4px 8px}.vet-banner button{margin-left:auto}.vet-warning{font-size:10px;color:#9a3412;margin-top:5px}.year-select-note{font-size:10px;color:var(--m);margin-top:4px}
@media(max-width:700px){.aurora-top-logo{float:none;display:block;margin:0 0 8px}.vet-banner .route{align-items:flex-start}.vet-banner button{margin-left:0;width:100%}}
`;document.head.appendChild(sty);

function brand(){let mark=q('.mark');if(mark)mark.innerHTML=`<img class="aurora-brand-logo" src="${LOGO}" alt="Aurora">`;let br=q('.brand');if(br&&!br.querySelector('.aurora-brand-logo'))br.insertAdjacentHTML('afterbegin',`<img class="aurora-brand-logo" src="${LOGO}" alt="Aurora">`);let top=q('.top>div:first-child');if(top&&!top.querySelector('.aurora-top-logo'))top.insertAdjacentHTML('afterbegin',`<img class="aurora-top-logo" src="${LOGO}" alt="Aurora">`)}
brand();

const nativeOpen=window.open.bind(window);window.open=function(url,...args){let w=nativeOpen(url,...args);if(w&&(!url||url==='about:blank')){try{let ow=w.document.write.bind(w.document);w.document.write=(html)=>{let h=String(html);const css=`<style>.aurora-pdf-logo{width:105px;height:62px;object-fit:contain}.aurora-pdf-brand{display:flex;align-items:center;gap:12px;border-bottom:2px solid #0f766e;padding-bottom:8px;margin-bottom:12px}.aurora-pdf-brand .school{font-size:11px;font-weight:700;color:#0f766e}.aurora-pdf-brand .school b{display:block;font-size:14px;color:#111;margin-top:2px}</style>`;if(h.includes('</head>'))h=h.replace('</head>',css+'</head>');const head=`<div class="aurora-pdf-brand"><img class="aurora-pdf-logo" src="${LOGO}"><div class="school">BERÇÁRIO E CRECHE ESCOLA AURORA<b>Gestão Escolar 2027</b></div></div>`;if(h.includes('<body>'))h=h.replace('<body>','<body>'+head);else if(h.includes('<body '))h=h.replace(/<body([^>]*)>/,'<body$1>'+head);return ow(h)}}catch{}return w};

async function vetApi(action,x={}){let r=await fetch(VET_API,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action,...x}),cache:'no-store'}),d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'veteran_api_failed');return d}
async function secData(){if(VSEC)return VSEC;VSEC=await api('secretary');return VSEC}
function nextClass(c){let x=norm(c);if(x==='bercario')return'Infantil I';if(x==='infantil i')return'Infantil II';if(x==='infantil iii a'||x==='infantil iii b'||x==='infantil iii')return'Infantil IV';if(x==='infantil iv')return'Infantil V';return''}
function setv(id,v){let e=q(id);if(!e||v===null||v===undefined)return;if(e.type==='checkbox')e.checked=!!v;else e.value=String(v)}
function setSelect(id,v){let e=q(id);if(!e||!v)return false;let op=[...e.options].find(o=>norm(o.value)===norm(v)||norm(o.textContent).startsWith(norm(v)));if(op){e.value=op.value;return true}return false}
function fillProfile(p){if(!p)return;setv('#raPreferido',p.nome_preferencial);setv('#raNasc',p.data_nascimento);setv('#raCpf',p.cpf);setv('#raRg',p.rg);setv('#raCertidao',p.certidao_nascimento);setv('#raNacionalidade',p.nacionalidade);setv('#raNaturalidade',p.naturalidade);setv('#raUfNasc',p.uf_nascimento);setv('#raEscolaAnterior',p.escola_anterior);setv('#raCep',p.cep);setv('#raEndereco',p.endereco);setv('#raNumero',p.numero);setv('#raComplemento',p.complemento);setv('#raBairro',p.bairro);setv('#raCidade',p.cidade);setv('#raUf',p.uf);setv('#raEmergNome',p.contato_emergencia_nome);setv('#raEmergParentesco',p.contato_emergencia_parentesco);setv('#raEmergTelefone',p.contato_emergencia_telefone);setv('#raAlergias',p.alergias);setv('#raMedicacao',p.medicacao);setv('#raSaude',p.observacao_saude);setv('#raApoio',p.apoio_especial);setv('#raAutorizados',p.autorizados_retirada);setv('#raObsSec',p.observacao_secretaria);setv('#raImg',p.autorizacao_imagem);setv('#raSaida',p.autorizacao_saida);setv('#raEmergCare',p.autorizacao_atendimento_emergencial)}
function fillGuardian(prefix,g){if(!g)return;setv(prefix+'Nome',g.nome);setv(prefix+'Parentesco',g.parentesco);setv(prefix+'Cpf',g.cpf);setv(prefix+'Rg',g.rg);setv(prefix+'Whatsapp',g.whatsapp);setv(prefix+'Telefone',g.telefone);setv(prefix+'Email',g.email);setv(prefix+'Profissao',g.profissao);setv(prefix+'Financeiro',g.responsavel_financeiro);setv(prefix+'Retirada',g.autorizado_retirada);setv(prefix+'Emergencia',g.contato_emergencia);setv(prefix+'Mora',g.mora_com_aluno)}
async function loadExistingItems(studentId){try{let r=await fetch(ITEMS_API9,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action:'list',studentId}),cache:'no-store'}),d=await r.json();if(!r.ok)return;for(const it of d.items||[]){if(it.source_type==='product'&&it.catalog_item_id){let row=q(`[data-product="${CSS.escape(it.catalog_item_id)}"]`),pick=row?.querySelector('.rfPick');if(!row||!pick)continue;pick.checked=true;row.querySelectorAll('.rfItemNeg,.rfQty,.rfVariant').forEach(x=>x.disabled=false);let qty=Number(it.quantidade||1),qi=row.querySelector('.rfQty'),ni=row.querySelector('.rfItemNeg'),vi=row.querySelector('.rfVariant');if(qi)qi.value=qty;if(ni)ni.value=qty?Number(it.valor_negociado||0)/qty:Number(it.valor_negociado||0);if(vi&&String(it.item||'').includes('valor alternativo'))vi.value='alternativo'}}document.querySelectorAll('.rfPick').forEach(c=>c.dispatchEvent(new Event('change')))}catch{}}
async function chooseVeteran(s){let form=q('#regForm');if(!form)return;form.dataset.veteranId=s.id;setv('#raNome',s.aluno);setSelect('#raTipo','Veterano');setSelect('#raAno','2027');let d=await secData(),p=(d.profiles||[]).find(x=>x.student_id===s.id),gs=(d.guardians||[]).filter(x=>x.student_id===s.id).sort((a,b)=>Number(b.principal)-Number(a.principal)),ens=(d.enrollments||[]).filter(x=>x.student_id===s.id).sort((a,b)=>Number(b.ano_letivo)-Number(a.ano_letivo));fillProfile(p);if(gs.length){fillGuardian('#rg1',gs[0]);fillGuardian('#rg2',gs[1])}else setv('#rg1Nome',s.responsavel||'');let prev=ens.find(x=>Number(x.ano_letivo)===2026)||ens[0],current=prev?.serie||s.turma,proposed=nextClass(current),tur=q('#raTurma');let chosen='';if(proposed&&setSelect('#raTurma',proposed))chosen=q('#raTurma').value;else if(setSelect('#raTurma',current))chosen=q('#raTurma').value;else if(tur)tur.value='';q('#raTurma')?.dispatchEvent(new Event('change'));let turn=prev?.turno||s.turno;if(turn)setSelect('#raTurno',turn);let oldMod=prev?.modalidade||s.servico;if(oldMod&&[...q('#raModalidade').options].some(o=>norm(o.value)===norm(oldMod))){setSelect('#raModalidade',oldMod);q('#raModalidade').dispatchEvent(new Event('change'))}let e27=ens.find(x=>Number(x.ano_letivo)===2027);if(e27){setSelect('#raTurma',e27.serie);q('#raTurma')?.dispatchEvent(new Event('change'));setSelect('#raTurno',e27.turno);setSelect('#raModalidade',e27.modalidade);q('#raModalidade')?.dispatchEvent(new Event('change'));setv('#rfMat',e27.valor_matricula);setv('#rfNeg',e27.mensalidade_negociada);setv('#rfVenc',e27.dia_vencimento);setSelect('#rfForma',e27.forma_pagamento);setSelect('#rfStatus',e27.status_financeiro);setv('#rfObs',e27.observacao_financeira);await loadExistingItems(s.id)}let banner=q('#vetBanner');if(banner){banner.classList.add('show');banner.innerHTML=`<b>✓ Veterano encontrado — dados carregados para conferência</b><div class="route"><span class="chip">2026: ${esc(current||'turma não informada')}</span><span>→</span><span class="chip">2027: ${esc(e27?.serie||chosen||'selecione a nova turma')}</span><button type="button" id="vetClear" class="btn ghost">Cadastrar como novo</button></div><div class="vet-warning">O histórico de 2026 será preservado. As alterações de turma, turno, modalidade e valores serão registradas na matrícula 2027.</div>`;q('#vetClear').onclick=()=>{form.dataset.veteranId='';banner.classList.remove('show');setSelect('#raTipo','Novato')}}q('#vetSuggest')?.classList.remove('open')}
function suggestions(){let input=q('#raNome'),box=q('#vetSuggest');if(!input||!box)return;let term=norm(input.value);if(term.length<2){box.classList.remove('open');return}let arr=(S.students||[]).filter(s=>norm(s.aluno).includes(term)).slice(0,8);box.innerHTML=arr.map(s=>`<div class="vet-option" data-id="${esc(s.id)}"><b>${esc(s.aluno)}</b><span>${esc(s.turma||'')} · ${esc(s.servico||'')} · ${esc(s.responsavel||'')}</span></div>`).join('')||'<div class="vet-option"><span>Nenhum veterano encontrado. O cadastro seguirá como aluno novo.</span></div>';box.classList.toggle('open',!!arr.length);box.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{let s=(S.students||[]).find(a=>a.id===x.dataset.id);if(s)chooseVeteran(s)})}
function buildPayload(){let g1={nome:val('#rg1Nome'),parentesco:val('#rg1Parentesco'),cpf:val('#rg1Cpf'),rg:val('#rg1Rg'),whatsapp:val('#rg1Whatsapp'),telefone:val('#rg1Telefone'),email:val('#rg1Email'),profissao:val('#rg1Profissao'),responsavelFinanceiro:chk('#rg1Financeiro'),autorizadoRetirada:chk('#rg1Retirada'),contatoEmergencia:chk('#rg1Emergencia'),moraComAluno:chk('#rg1Mora'),principal:true},g2={nome:val('#rg2Nome'),parentesco:val('#rg2Parentesco'),cpf:val('#rg2Cpf'),rg:val('#rg2Rg'),whatsapp:val('#rg2Whatsapp'),telefone:val('#rg2Telefone'),email:val('#rg2Email'),profissao:val('#rg2Profissao'),responsavelFinanceiro:chk('#rg2Financeiro'),autorizadoRetirada:chk('#rg2Retirada'),contatoEmergencia:chk('#rg2Emergencia'),moraComAluno:chk('#rg2Mora'),principal:false};return{student:{aluno:val('#raNome'),turma:val('#raTurma'),turno:val('#raTurno'),modalidade:val('#raModalidade'),responsavel:g1.nome},profile:{nomePreferencial:val('#raPreferido'),dataNascimento:val('#raNasc'),cpf:val('#raCpf'),rg:val('#raRg'),certidaoNascimento:val('#raCertidao'),nacionalidade:val('#raNacionalidade'),naturalidade:val('#raNaturalidade'),ufNascimento:val('#raUfNasc'),escolaAnterior:val('#raEscolaAnterior'),cep:val('#raCep'),endereco:val('#raEndereco'),numero:val('#raNumero'),complemento:val('#raComplemento'),bairro:val('#raBairro'),cidade:val('#raCidade'),uf:val('#raUf'),contatoEmergenciaNome:val('#raEmergNome'),contatoEmergenciaParentesco:val('#raEmergParentesco'),contatoEmergenciaTelefone:val('#raEmergTelefone'),alergias:val('#raAlergias'),medicacao:val('#raMedicacao'),observacaoSaude:val('#raSaude'),apoioEspecial:val('#raApoio'),autorizacaoImagem:chk('#raImg'),autorizacaoSaida:chk('#raSaida'),autorizacaoAtendimentoEmergencial:chk('#raEmergCare'),autorizadosRetirada:val('#raAutorizados'),observacaoSecretaria:val('#raObsSec')},guardians:[g1,g2],enrollment:{anoLetivo:val('#raAno')||2027,tipoAluno:'Veterano',dataMatricula:val('#raDataMat'),dataInicio:val('#raDataInicio'),status:val('#raStatus'),origemAtendimento:val('#raOrigem')||'rematricula',atendente:val('#raAtendente'),whatsapp:g1.whatsapp,telefone:g1.telefone,email:g1.email,valorMatricula:val('#rfMat'),mensalidadeTabela:val('#rfTabela'),mensalidadeNegociada:val('#rfNeg'),servicosExtras:val('#rfExtras'),diaVencimento:val('#rfVenc'),formaPagamento:val('#rfForma'),statusFinanceiro:val('#rfStatus'),observacaoFinanceira:val('#rfObs')}}}
function collectItems(){let items=[],turma=val('#raTurma'),mod=val('#raModalidade'),rate=(S.monthlyRates||[]).find(r=>r.turma===turma&&r.servico===mod);if(rate)items.push({sourceType:'monthly_rate',sourceId:rate.id,quantity:1,negotiated:nn(val('#rfNeg'))});for(const c of document.querySelectorAll('.rfPick:checked')){let id=c.dataset.id,row=q(`[data-product="${CSS.escape(id)}"]`);if(!row)continue;items.push({sourceType:'product',sourceId:id,variant:row.querySelector('.rfVariant')?.value||'normal',quantity:nn(row.querySelector('.rfQty')?.value)??1,negotiated:nn(row.querySelector('.rfItemNeg')?.value)})}let mat=nn(val('#rfMat'));if(mat&&mat>0)items.push({sourceType:'manual',item:'Matrícula',quantity:1,table2027:mat,negotiated:mat});return items}
async function saveItems(studentId,items){let r=await fetch(ITEMS_API9,{method:'POST',headers:{'content-type':'application/json','x-aurora-password':P},body:JSON.stringify({action:'save',studentId,items}),cache:'no-store'}),d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'items_save_failed');return d}
async function submitVeteran(e,oldSubmit){let form=q('#regForm'),studentId=form?.dataset.veteranId;if(!studentId)return oldSubmit.call(form,e);e.preventDefault();let btn=q('#regSave');btn.disabled=true;btn.textContent='Salvando rematrícula...';try{let payload=buildPayload(),items=collectItems(),r=await vetApi('reenroll',{studentId,payload});V=r.version;let ir=await saveItems(studentId,items);let d=await api('get');S=d.state;V=d.version;VSEC=null;toast(`✓ Veterano atualizado: ${r.matricula} · ${ir.count} itens financeiros`);show('records')}catch(x){toast('Não foi possível concluir a rematrícula: '+x.message,true)}finally{btn.disabled=false;btn.textContent='Salvar rematrícula 2027'}}
function enhance(){brand();let input=q('#raNome'),form=q('#regForm');if(!input||!form||form.dataset.v9==='1')return;form.dataset.v9='1';let field=input.closest('.field');if(field){field.classList.add('name-field-wrap');field.insertAdjacentHTML('beforeend','<div id="vetSuggest" class="vet-suggest"></div><div id="vetBanner" class="vet-banner"></div>')}input.setAttribute('autocomplete','off');input.addEventListener('input',()=>{if(form.dataset.veteranId&&norm((S.students||[]).find(x=>x.id===form.dataset.veteranId)?.aluno)!==norm(input.value)){form.dataset.veteranId='';q('#vetBanner')?.classList.remove('show')}suggestions()});input.addEventListener('focus',suggestions);document.addEventListener('click',ev=>{if(!field?.contains(ev.target))q('#vetSuggest')?.classList.remove('open')},{once:false});let old=form.onsubmit;form.onsubmit=e=>submitVeteran(e,old);let type=q('#raTipo');if(type)type.onchange=()=>{if(type.value==='Novato'){form.dataset.veteranId='';q('#vetBanner')?.classList.remove('show')}}}
const oldReg=R.register;R.register=()=>{oldReg();setTimeout(enhance,40)};

async function classRows(turma){let d=await vetApi('classList',{year:2027,turma});return d.rows||[]}
function renderAttV9(){let ts=[...new Set((S.monthlyRates||[]).map(r=>r.turma).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),today=new Date().toISOString().slice(0,10);q('#attendance').innerHTML=sec('Frequência 2027','A chamada usa a matrícula 2027 do aluno.')+`<div class="att-toolbar"><div class="field"><label>Data</label><input id="v9AttDate" type="date" value="${today}"></div><div class="field"><label>Turma 2027</label><select id="v9AttClass">${options(ts,'','Selecione a turma')}</select></div><button id="v9AttLoad" class="btn">Carregar turma</button><button id="v9AttPrint" class="btn ghost" disabled>Imprimir/PDF</button></div><div id="v9AttBody" class="card"><div class="mini">Somente alunos matriculados/rematriculados em 2027 aparecem nesta lista.</div></div>`;q('#v9AttLoad').onclick=async()=>{let turma=val('#v9AttClass');if(!turma)return toast('Selecione a turma.',true);let rows=await classRows(turma);q('#v9AttBody').innerHTML=`<div class="tablebox"><table class="tbl att-table"><thead><tr><th>Aluno</th><th>Responsável</th><th>Status</th><th>Entrada</th><th>Saída</th><th>Observação</th></tr></thead><tbody>${rows.map(r=>`<tr data-att="${esc(r.id)}"><td><b>${esc(r.aluno)}</b><div class="mini">${esc(r.servico||'')}</div></td><td>${esc(r.responsavel||'')}</td><td><select class="v9st"><option value="presente">Presente</option><option value="falta">Falta</option><option value="justificada">Falta justificada</option><option value="atraso">Atraso</option></select></td><td><input class="v9in" type="time"></td><td><input class="v9out" type="time"></td><td><input class="v9obs"></td></tr>`).join('')}</tbody></table></div><div class="formactions"><button id="v9AttSave" class="btn">Salvar frequência</button></div>`;q('#v9AttPrint').disabled=!rows.length;q('#v9AttPrint').onclick=()=>printList('Lista de Frequência',turma,rows);q('#v9AttSave').onclick=async()=>{let data=val('#v9AttDate'),payload=[...document.querySelectorAll('[data-att]')].map(tr=>({studentId:tr.dataset.att,status:tr.querySelector('.v9st').value,horaEntrada:tr.querySelector('.v9in').value,horaSaida:tr.querySelector('.v9out').value,observacao:tr.querySelector('.v9obs').value}));await api('saveAttendance',{data,rows:payload});toast('✓ Frequência salva')}}}
function printList(title,turma,rows,signature=false){let w=window.open('','_blank');if(!w)return;let data=signature?val('#v9SigDate'):val('#v9AttDate');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:12mm}body{font-family:Arial,sans-serif;color:#111;font-size:12px}h1{font-size:20px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #999;padding:7px;text-align:left}th{background:#eee}.line{height:42px}</style></head><body><h1>${esc(title)}</h1><p><b>Turma:</b> ${esc(turma)} &nbsp; <b>Data:</b> ${esc(data)}</p><table><tr><th>#</th><th>Aluno</th><th>Responsável</th><th>${signature?'Assinatura':'Presença / Observação'}</th></tr>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.aluno)}</td><td>${esc(r.responsavel||'')}</td><td class="line"></td></tr>`).join('')}</table></body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print()},500)}
function renderSigV9(){let ts=[...new Set((S.monthlyRates||[]).map(r=>r.turma).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));q('#signatures').innerHTML=sec('Lista de assinaturas 2027','Gerada pela turma atual da matrícula 2027.')+`<div class="att-toolbar"><div class="field"><label>Data</label><input id="v9SigDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Turma 2027</label><select id="v9SigClass">${options(ts,'','Selecione a turma')}</select></div><div class="field"><label>Título</label><input id="v9SigTitle" value="Lista de Assinaturas"></div><button id="v9SigGen" class="btn">Gerar</button></div><div id="v9SigBody" class="print-preview"><div class="mini">Somente alunos com matrícula 2027 aparecem.</div></div>`;q('#v9SigGen').onclick=async()=>{let turma=val('#v9SigClass');if(!turma)return toast('Selecione a turma.',true);let rows=await classRows(turma),title=val('#v9SigTitle')||'Lista de Assinaturas';q('#v9SigBody').innerHTML=`<div class="sec"><div><h2>${esc(title)}</h2><p>${esc(turma)}</p></div><button id="v9SigPrint" class="btn ghost">Imprimir/PDF</button></div><table class="signature-table"><thead><tr><th>#</th><th>Aluno</th><th>Responsável</th><th>Assinatura</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.aluno)}</td><td>${esc(r.responsavel||'')}</td><td class="signature-line"></td></tr>`).join('')}</tbody></table>`;q('#v9SigPrint').onclick=()=>printList(title,turma,rows,true)}}
R.attendance=renderAttV9;R.signatures=renderSigV9;
})();